//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shiftgram.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Bio { get; set; }
        public string Username { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> PhoneId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Phone Phone { get; set; }
    }
}
